apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name:  binary_scan

jobs:
  scan:
    steps:
      - name: Initiate execution plan
        uses: docker://docker.preprod.ecr/actions/assets-plugin-chain-utils:5027673eb01bf99931a5a181bdc2cffbd985a908
        id: plan
        with:
          entrypoint: assets-plugin-chain-utils
          args: configure
        env:
          INPUT_CLOUDBEES_API_TOKEN: ${{ cloudbees.api.token }}
          INPUT_CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
          INPUT_RUN_ID: ${{ cloudbees.run_id }}
          INPUT_PLUGIN_LIST: 'trivy,findsecbugs,syft,grype'
      - name: Workflow Artifact Inventory
        if: ${{ steps.plan.outputs.wfartifact-inventory == 'true' }}
        env:
          INPUT_CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
          INPUT_WF_ARTIFACT_TOKEN: ${{ steps.plan.outputs.wf_artifact_token }}
          INPUT_COMPONENT_ID: ${{ steps.plan.outputs.wf_artifact_component_id }}
          EXECUTION_ROLE: "MASTER"
        uses: docker://docker.preprod.ecr/actions/assets-cbp-workflow-artifacts:latest
        run: /app/plugin-cbp-workflow-artifacts -mode single
      - name: Workflow Artifact Metadata
        if: ${{ steps.plan.outputs.wfartifact-decorator == 'true' }}
        env:
          INPUT_CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
          INPUT_WF_ARTIFACT_TOKEN: ${{ steps.plan.outputs.wf_artifact_token }}
          INPUT_COMPONENT_ID: ${{ steps.plan.outputs.wf_artifact_component_id }}
          EXECUTION_ROLE: "DECORATOR"
        uses: docker://docker.preprod.ecr/actions/assets-cbp-workflow-artifacts:latest
        run: /app/plugin-cbp-workflow-artifacts -mode single

      - name: Trivy Scanner
        if: ${{ steps.plan.outputs.trivy == 'true' }}
        uses: docker://docker.preprod.ecr/actions/assets-trivy-scanner:latest
        continue-on-error: true
        run: /app/plugin-trivy-scanner -mode single

      - name: FindSecBugs Scanner
        if: ${{ steps.plan.outputs.findsecbugs == 'true' }}
        uses: docker://docker.preprod.ecr/actions/assets-findsecbugs-scanner:latest
        continue-on-error: true
        run: /app/plugin-findsecbugs -mode single

      - name: Syft SBOM analyser
        if: ${{ steps.plan.outputs.syft == 'true' }}
        uses: docker://docker.preprod.ecr/actions/assets-syft-sbom:latest
        continue-on-error: true
        run: /app/plugin-syftbom-analyser -mode single

      - name: Grype Scanner
        if: ${{ steps.plan.outputs.grype == 'true' }}
        uses: docker://docker.preprod.ecr/actions/assets-grype-scanner:24c5c03b4793488b64cfb076262f28b81727cdf6
        continue-on-error: true
        run: /app/plugin-grype-scanner -mode single

      - name: Complete execution plan
        uses: docker://docker.preprod.ecr/actions/assets-plugin-chain-utils:5027673eb01bf99931a5a181bdc2cffbd985a908
        id: process-outputs
        with:
          entrypoint: assets-plugin-chain-utils
          args: process-outputs
        env:
          INPUT_CLOUDBEES_API_TOKEN: ${{ cloudbees.api.token }}
          INPUT_CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
          INPUT_RUN_ID: ${{ cloudbees.run_id }}