apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name:  scan

jobs:
  scan:
    steps:
      - name: Initiate execution plan
        uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/assets-plugin-chain-utils:77876b3e840c3fd7596486a3e9c4ac3d860edee7
        id: plan
        with:
          entrypoint: assets-plugin-chain-utils
          args: configure
        env:
          INPUT_CLOUDBEES_API_TOKEN: ${{ cloudbees.api.token }}
          INPUT_CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
          INPUT_RUN_ID: ${{ cloudbees.run_id }}
          INPUT_PLUGIN_LIST: 'gosec,njsscan,gitleaks'
      - name: Github Inventory
        if: ${{ steps.plan.outputs.github-master == 'true' }}
        uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/assets-github-inventory:latest
        env:
          ACCOUNT_CREDENTIALS: ${{ steps.plan.outputs.account_credentials}}
        run: /app/plugin-git-master -mode single

      - name: Github Metadata
        if: ${{ steps.plan.outputs.github-decorator == 'true' }}
        uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/assets-github-metadata:latest
        env:
          ACCOUNT_CREDENTIALS: ${{ steps.plan.outputs.account_credentials}}
        run: /app/plugin-git-decorator -mode single

      - name: SCC Scanner
        if: ${{ steps.plan.outputs.scc == 'true' }}
        uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/assets-scc-scanner:latest
        run: /app/plugin-scc-scanner -mode single

      - name: GoSec Scanner
        if: ${{ steps.plan.outputs.gosec == 'true' }}
        uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/assets-gosec-scanner:latest
        continue-on-error: true
        run: /app/plugin-gosec-scanner -mode single

      - name: Njs Scanner
        if: ${{ steps.plan.outputs.njsscan == 'true' }}
        uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/assets-njsscan-scanner:latest
        continue-on-error: true
        run: /app/plugin-njsscan-scanner -mode single

      - name: Gitleaks Scanner
        if: ${{ steps.plan.outputs.gitleaks == 'true' }}
        uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/assets-gitleaks-scanner:latest
        env:
          RUN_ID: ${{ cloudbees.run_id }}
          JOB_ID: ${{ job.id }}
          STEP_ID: ${{ step.internal.id }}
        continue-on-error: true
        run: /app/plugin-gitleaks-scanner -mode single

      - name: Complete execution plan
        uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/assets-plugin-chain-utils:latest
        id: process-outputs
        with:
          entrypoint: assets-plugin-chain-utils
          args: process-outputs
        env:
          INPUT_CLOUDBEES_API_TOKEN: ${{ cloudbees.api.token }}
          INPUT_CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
          INPUT_RUN_ID: ${{ cloudbees.run_id }}